name: 'Deploy to GitHub Pages'
on:
  push:
    branches:
      - master
jobs:
  gh-pages-deploy:
    name: Deploying to Github Pages
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: '12'
        - name: Install packages
          run: npm i
        - name: Set Creds
          run: git config user.name "slothbearsteven" && git config user.email "kennedy.steven.p@gmail.com"
        - name: Deploy
          run: |
            git checkout --orphan gh-pages \
              echo 'Building started...' \
              npm run build \
              git --work-tree dist add --all \
              git --work-tree dist commit -m "gh-pages" \
              echo "Pushing to gh-pages..." \
              git push origin HEAD:gh-pages --force \
              rm -r dist \
              git checkout -f master \ 
              git branch -D gh-pages \
              echo "Successfully deployed, check your settings"
